config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#redirect_to_welcome' 
  get '/welcome' => 'pages#index'
  
  # These routes are for showing users a login form, logging them in, and logging them out:
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  # These routes will be for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user:
  resources :users
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  # This route is for showing users their dashboard:
  get '/dashboard' => 'dashboards#show'
  post '/dashboard' => 'dashboards#show'
  post 'filter_dids', to: 'dashboards#filter_dids', as: :filter_dids
  post 'reassign_dids', to: 'dashboards#reassign_dids', as: :reassign_dids
  
  # These routes are used for email validation links:
  get '/emailconfirmation' => 'email_confirmations#update'
  get '/sendemailverify' => 'email_confirmations#create'
  
  # These routes are used for forgetten password resets:
  get 'password_resets/new'
  get '/passwordreset' => 'password_resets#edit'
  post '/passwordreset' => 'password_resets#update'
  get '/requestreset' => 'password_resets#new'
  post '/requestreset' => 'password_resets#create'
  
  resources :verticals
  
  resources :sources
  
  resources :funnels
  put 'funnel_buy_dids', to: 'funnels#buy_dids', as: :funnel_buy_dids
  
  resources :campaigns do
		member do
			get :contact_history
		end
	end
  
  get '/contacts' => 'contacts#index'
  put '/contacts' => 'contacts#update'
  
  get '/backoffice' => 'backoffice#index'
  
  resources :globals, controller: 'backoffice'
	
	patch '/backoffice' => 'backoffice#update'
	
	resources :backoffice
  
  resources :charges
	
	resources :ivrs
end

app/models/vertical.rb
class Vertical < ApplicationRecord
  belongs_to :user
  has_many :campaigns

  validates_uniqueness_of :name, scope: [:user_id]
end

app/controllers/verticals_controller.rb
class VerticalsController < ApplicationController
  
  def index
  end
  
  def new
    @vertical = current_user.verticals.new
  end
  
  def create
    current_user.verticals.create(vertical_params)
  end
  
  def edit
    @vertical = Vertical.find(params[:id])
  end
  
  def update
    @vertical = Vertical.find(params[:id])
    @vertical.update_attributes(vertical_params)
  end
  
  def destroy
    vertical = Vertical.find(params[:id])
    vertical.destroy
  end
  
  private
  
  def vertical_params
    params.require(:vertical).permit(:name)
  end
end

app/helpers/verticals_helper.rb
module VerticalsHelper
end

app/views/verticals/_edit.html.erb
<%= form_for :vertical, url: vertical_path, method: :put, remote: true do |f| %>
  <table class="table" id="verticals_table">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% current_user.verticals.each do |vertical| %>
        <tr id='<%= vertical.name%>'>
          <% if vertical.id == @vertical.id %>
            <td><%= f.text_field :name, class: 'form-control' %></td>
            <td style="vertical-align: top;"><%= f.submit 'Update', class: 'btn btn-primary' %></td>
          <% else %>
            <td><%= vertical.name%></td>
            <td><%= link_to 'Edit', edit_vertical_path(id: vertical.id), remote: true, style: 'color:black;' %> / <%= link_to 'Delete', verticals_path(id: vertical.id), method: :delete, remote: true, style: 'color:black;' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/verticals/_index.html.erb
<h3>Dashboard / Verticals / <%= link_to "Add New <i class='fa fa-plus-circle'></i>".html_safe, new_vertical_path, remote: true, style: 'color:#1da3ed;' %></h3>
<p>Some helpful Verticals text. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<div class="orderBox">
  <h4>Verticals</h4>
  <div class="table-responsive">
    <table class="table" id="verticals_table">
      <thead>
        <tr>
          <th>Name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% current_user.verticals.each do |vertical| %>
          <tr id='<%= vertical.name%>'>
            <td><%= vertical.name%></td>
            <td><%= link_to 'Edit', edit_vertical_path(id: vertical.id), remote: true, style: 'color:black;' %> / <%= link_to 'Delete', vertical_path(id: vertical.id), method: :delete, remote: true, style: 'color:black;' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/verticals/_new.html.erb
<%= form_for :vertical, url: verticals_path(@vertical), method: :post, remote: true do |f| %>
  <table class="table" id="verticals_table">
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% current_user.verticals.each do |vertical| %>
        <% if vertical.id.blank? %>
          <tr>
            <td><%= f.text_field :name, class: 'form-control' %></td>
            <td style="vertical-align: top;"><%= f.submit 'Create', class: 'btn btn-primary' %></td>
          </tr>
        <% else %>
        <tr id='<%= vertical.name%>'>
          <td><%= vertical.name%></td>
          <td><%= link_to 'Edit', edit_vertical_path(id: vertical.id), remote: true, style: 'color:black;' %> / <%= link_to 'Delete', verticals_path(id: vertical.id), method: :delete, remote: true, style: 'color:black;' %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/verticals/create.js.erb
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");

app/views/verticals/destroy.js.erb
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");

app/views/verticals/edit.js.erb
$("#verticals_table").replaceWith("<%= j render partial: 'edit' %>");

app/views/verticals/index.js.erb
$("#dashboard_menu").replaceWith("<div id='dashboard_menu'> <%= j render partial: '/dashboards/menu' %> </div>");
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");

app/views/verticals/new.js.erb
$("#verticals_table").replaceWith("<%= j render partial: 'new' %>");

app/views/verticals/update.js.erb
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");