config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#redirect_to_welcome' 
  get '/welcome' => 'pages#index'
  
  # These routes are for showing users a login form, logging them in, and logging them out:
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  # These routes will be for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user:
  resources :users
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  # This route is for showing users their dashboard:
  get '/dashboard' => 'dashboards#show'
  post '/dashboard' => 'dashboards#show'
  post 'filter_dids', to: 'dashboards#filter_dids', as: :filter_dids
  post 'reassign_dids', to: 'dashboards#reassign_dids', as: :reassign_dids
  
  # These routes are used for email validation links:
  get '/emailconfirmation' => 'email_confirmations#update'
  get '/sendemailverify' => 'email_confirmations#create'
  
  # These routes are used for forgetten password resets:
  get 'password_resets/new'
  get '/passwordreset' => 'password_resets#edit'
  post '/passwordreset' => 'password_resets#update'
  get '/requestreset' => 'password_resets#new'
  post '/requestreset' => 'password_resets#create'
  
  resources :verticals
  
  resources :sources
  
  resources :funnels
  put 'funnel_buy_dids', to: 'funnels#buy_dids', as: :funnel_buy_dids
  
  resources :campaigns do
		member do
			get :contact_history
		end
	end
  
  get '/contacts' => 'contacts#index'
  put '/contacts' => 'contacts#update'
  
  get '/backoffice' => 'backoffice#index'
  
  resources :globals, controller: 'backoffice'
	
	patch '/backoffice' => 'backoffice#update'
	
	resources :backoffice
  
  resources :charges
	
	resources :ivrs
end

app/models/funnel.rb
class Funnel < ApplicationRecord
  belongs_to :user
  belongs_to :vertical, optional: true
  has_and_belongs_to_many :campaigns, optional: true, after_remove: :check_remote_agents
  has_many :dids, autosave: true
	has_many :funnel_ivrs
	has_many :ivrs, through: :funnel_ivrs
  accepts_nested_attributes_for :campaigns
  accepts_nested_attributes_for :dids
  validates_presence_of :name, message: 'Name cannot be blank.'
  validates_presence_of :routing_type, message: 'You must select a routing type.'
  validates_presence_of :vertical_id, message: 'You must select a vertical.'
  validates_presence_of :did_ids, message: 'You must pick an available inbound DID.', if: :bulk_did_purchase?
  validates_presence_of :campaign_ids, message: 'You must select a destination.'
  validate :has_enough_balance
  after_commit :setup_vicidial, on: [:create, :update]
  before_destroy :remove_vicidial_ingroup, prepend: true
  after_destroy :check_remote_agents
	
	attr_accessor :bulk_dids
	attr_accessor :toll_free
	attr_accessor :selected_states
  
  enum routing_type: [:round_robin, :priority]
	
  def has_enough_balance
    if bulk_did_purchase?
      number_of_dids = self.bulk_dids.to_i
    else
      number_of_dids = 1
    end
    
    subtotal = 0.0
    if self.toll_free.to_i > 0
      subtotal = Global.where(name: 'default_tfn_price').first.value.to_d * number_of_dids
    else
      subtotal = Global.where(name: 'default_local_did_price').first.value.to_d * number_of_dids
    end
    
    if self.user.enough_cash?(subtotal)
      return true
    else
      errors.add(:check_your_balance, 'Your account does not have enough funds for your DID purchase.')
      return false
    end  
  end
  
	def bulk_did_purchase?
		self.bulk_dids.to_i == 0
	end
  
  def setup_vicidial
    # 1: Ensure Vicidial ingroups are set:
    if self.vicidial_ingroup_id.blank?
      Vicidial.default_api.add_ingroup(self)
    end
    
    # 2: Ensure each remote agent is set:
    self.campaigns.each do |campaign|
      if campaign.vicidial_remote_agent?
        Vicidial.default_api.update_remote_agent(campaign)
      else
        Vicidial.default_api.add_remote_agent(campaign)
      end
    end
    
    # 3: Set up inbound area code blocking if defined by camapign/destination:
    Vicidial.default_api.update_filter_phone_group(self) unless self.dids.first.blank?
  end
  
  def remove_vicidial_ingroup
    Vicidial.default_api.delete_ingroup(self) unless self.vicidial_ingroup_id.blank?
    
    self.dids.each do |did|
      Vicidial.default_api.update_did(did)
    end
  end
  
  def check_remote_agents
    self.user.campaigns.each do |campaign|
      Vicidial.default_api.update_remote_agent(campaign) if campaign.funnels.blank?
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token :confirm_token
  has_secure_token :password_reset_token
  attr_accessor :remember_token
	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
  has_many :sources
  has_many :funnels
  has_many :dids, through: :funnels
  has_many :verticals
  has_many :charges
  has_many :campaigns, through: :verticals
  has_many :agents, through: :campaigns
	has_many :ivrs
  after_commit :set_defaults, on: [:create]
  
  # Returns the hash digest of the given string:
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions:
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def send_email_confirmation
    UserMailer.email_confirmation(self).deliver
  end
  
  def send_buyer_email_confirmation
    UserMailer.email_buyer_confirmation(self).deliver
  end
  
  def send_password_reset
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def enough_cash?(purchase_amount)
    if self.balance >= purchase_amount
      return true
    else
      return false
    end
  end
  
  # Here's where we populate some useful defaults for new users:
  def set_defaults
    vertical_names = [
      'Auto Finance',
      'Auto Insurance (Basic)',
      'Auto Insurance (Advanced)',
      'Auto Warranty',
      'Byetta',
      'Debt Consolidation',
      'Diabetic',
      'Education',
      'Granuflo',
      'Health Insurance',
      'Hip Replacement',
      'Home Improvement',
      'Life Insurance',
      'Low Testosterone',
      'Mortgage',
      'Mortgage Refinance',
      'New Car Purchase',
      'Pain Cream',
      'Payday (US)',
      'Payday (UK)',
      'Satellite Television',
      'Social Security Disability (SSD)',
      'Tax Debt',
      'Transvaginal Mesh (TVM)',
      'Yaz/Yasmin/Ocella'
    ]
    vertical_names.each do |vertical_name|
      self.verticals.create(name: vertical_name)
    end
    
    source_names = [
      'Email',
      'Ringless Voicemail',
      'SMS',
      'Call Center',
      'Media ',
      'Facebook ',
      'PPC',
      'Direct Mail'
    ]
    source_names.each do |source_name|
      self.sources.create(name: source_name)
    end
    
    #Set billing rate to the global default:
    self.billing_rate = Global.find_by_name('default_billing_rate').value
  end
  
end

app/controllers/funnels_controller.rb
class FunnelsController < ApplicationController
  
  def index
  end
  
  def new
    @funnel = current_user.funnels.new
  end
  
  def create
		logger.debug(current_user.inspect)
    @funnel = current_user.funnels.build(funnel_params)
		
    respond_to do |format|
      if @funnel.save
				if funnel_params['bulk_dids'].to_i > 0
					area_codes = ApplicationController.new.get_state_area_codes(funnel_params['selected_states'])
					area_codes = ['TFNS'] if funnel_params['toll_free'].to_i > 0
					BuyBulkDidJob.perform_later(@funnel.id, @funnel.name, funnel_params['bulk_dids'].to_i, area_codes)
				end
        format.js { flash[:notice] = 'The camapign has been added.' }
      else
        @error = true
        format.js { flash[:error] = @funnel.errors }
      end
    end
  end
  
  def edit
    @funnel = Funnel.find(params[:id])
  end
  
  def update
    @funnel = Funnel.find(params[:id])
    @funnel.update_attributes(funnel_params)
  end
  
  def buy_dids
    @funnel = Funnel.find_by_id(params[:funnel][:id])
    
    respond_to do |format|
      if @funnel.blank?
        @error = false
        format.js { flash[:error] = 'Please select a funnel for your bulk DID purchase.' }
      elsif params[:funnel][:bulk_dids].to_i == 0
        @error = true
        format.js { flash[:error] = 'The number of dids to purchase has to be greater than zero.' }
      else
        @funnel.bulk_dids = params[:funnel][:bulk_dids].to_i
        @funnel.toll_free = params[:funnel][:toll_free].to_i
        @funnel.selected_states = params[:funnel][:selected_states]
        if @funnel.has_enough_balance
					area_codes = ApplicationController.new.get_state_area_codes(@funnel.selected_states)
					area_codes = ['TFNS'] if @funnel.toll_free > 0
          BuyBulkDidJob.perform_later(@funnel.id, @funnel.name, funnel_params['bulk_dids'].to_i, area_codes)
          format.js { flash[:notice] = 'Your bulk DID purchase is being processed and you will receive an email report in a few minutes.' }
        else
          @error = true
          format.js { flash[:error] = 'Your account does not have enough funds for this DID purchase.' }
        end
      end
    end
  end
  
  def destroy
    funnel = Funnel.find(params[:id])
    funnel.destroy
  end
  
  private
  
  def funnel_params
    params.require(:funnel).permit(:name, :forwarding_number, :vertical_id, :routing_type, :mask_number, :did_ids, :bulk_dids, :toll_free, selected_states: [], campaign_ids: [])
  end
end

app/helpers/funnels_helper.rb
module FunnelsHelper
end

app/views/funnels/_buy_bulk_dids.html.erb
<%= form_for Funnel.new, url: funnel_buy_dids_path, method: :put, remote: true do |f| %>
  <div id="bulk_dids" role="tablist" aria-multiselectable="true">
    <div class="card card-accordion">
      <div class="card-header" role="tab" id="heading1">
        <h6 class="mb-0">
          <a data-toggle="collapse" data-parent="#bulk_dids" href="#collapse1" class="collapsed" aria-expanded="false" aria-controls="collapse1">
            Bulk Buy DIDs
          </a>
        </h6>
      </div>
      <div id="collapse1" class="collapse" role="tabpanel" aria-labelledby="collapse1">
        <div class="card-block col-md-6" style="border-width: 0px;">
          <label for='' class="col-form-label">Number of DIDs (max 1000, emailed CSV report)</label>
          <%= f.number_field :bulk_dids, class: 'form-control', value: '0', min: 0, max: 1000 %>
          <%= f.check_box :toll_free, class: 'checkbox-custom form-check-input' %>
          <label for='' class="checkbox-custom-label form-check-label">Toll Free DIDs</label>
          <div class="selectOptions">
            <label for='' class="col-form-label">Funnel</label>
            <%= f.collection_select :id, current_user.funnels, :id, :name, { prompt: 'Select Funnel' }, class: 'form-control select-drop' %>
          </div>
        </div>
        <div class='row'>
        </div>
        <div class="card-block" style="border-width: 0px;">
          <label for='' class="col-form-label">Select States (Local DIDs Only)</label><br />
          <%= f.collection_check_boxes :selected_states, states, :first, :first do |b| %>
            <div class="form-group col-md-3 float-left">
              <%= b.check_box class: 'checkbox-custom form-check-input' %>
              <%= b.label class: 'checkbox-custom-label form-check-label' %>
            </div>
          <% end %>
        </div>
        <div class='row'></div>
        <div class="row form-group col-md-3 float-left">
          <div id='bulk_buy_flash_messages'></div>
          <%= button_tag 'submit', class: 'btn btn-primary btn-block', name: 'bulk_buy_button', data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> Purchasing…" } do %>
            <i class="fa fa-circle-o-notch"></i> Purchase DIDs
          <% end %>
        </div>
        <div class='row'></div>
      </div>
    </div>
  </div>
<% end %>

app/views/funnels/_edit.html.erb
<%= form_for @funnel, url: funnel_path, method: :put, remote: true do |f| %>
  <div class="row" id="funnels_table">    
    <div class="form-group col-md-6">
      <label for='' class="col-form-label">Name</label>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group col-md-6"> 
      <label for='' class="col-form-label">Forwarding Number (Optional)</label>
      <%= f.telephone_field :forwarding_number, class: 'form-control' %>
    </div>
    <div class="from-group col-md-6">
      <div class="selectOptions">
        <label for='' class="col-form-label">Vertical</label>
        <%= f.select :vertical_id, current_user.verticals.collect { |v| [ v.name, v.id ] }, { prompt: 'Select Vertical' }, class: 'form-control select-drop' %>
      </div>
    </div>         
    <div class="from-group col-md-6">
      <div class="selectOptions">
        <label for='' class="col-form-label">Routing Type</label>
        <%= f.select :routing_type, Funnel.routing_types.keys.map { |f| [ f.humanize.titleize, f ] }, { prompt: 'Select Routing Type' }, class: 'form-control select-drop' %>
      </div>
    </div>
    <div class="from-group col-md-6">
      <% if current_user.campaigns.blank? %>
        <p></p>
      <% else %>
        <div class='display-single_element'>
          <p style='color:black;font-size:15px;margin-top:30px;'>Destinations</p>
          <div class='row'>
            <%= f.collection_check_boxes :campaign_ids, current_user.campaigns, :id, :name do |b| %>
              <div class="form-group col-md-6">
                <%= b.check_box class: 'checkbox-custom form-check-input' %>
                <%= b.label class: 'checkbox-custom-label form-check-label' %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="from-group col-md-6">
      <div class='display-single_element'>
        <p style='color:black;font-size:15px;margin-top:30px;'>Options</p>
        <div class='row'>
          <div class="from-group col-md-6">
            <%= f.check_box :mask_number, class: 'checkbox-custom form-check-input' %>
            <label for='' class="checkbox-custom-label form-check-label">Mask Number</label>
          </div>
        </div>
      </div>
    </div>        
    <div class="from-group col-md-6">
      <% if @funnel.dids.size < 2 %>
        <div class="selectOptions">
          <label for='' class="col-form-label">Change Inbound DID</label>
            <%= f.select :did_ids, Did.where(funnel_id: [nil, @funnel.id]).order(Arel.sql('RAND()')).limit(6).collect { |d| [ number_to_phone(d.number, area_code: true), d.id ] }, { prompt: '' }, Class: 'form-control select-drop' %>
        </div>
      <% else %>
        <div class='display-single_element'>
          <p style='color:black;font-size:15px;margin-top:30px;'>DIDs</p>
        </div>
        <div class='row'>
          <%= f.collection_check_boxes :did_ids, @funnel.dids, :id, :number do |b| %>
            <div class="form-group col-md-6">
              <%= b.check_box class: 'checkbox-custom form-check-input' %>
              <%= b.label(class: 'checkbox-custom-label form-check-label') { number_to_phone(b.text, area_code: true) } %>
            </div>
          <% end %>
        </div>
        
      <% end %>
    </div>
    
    <div class="from-group col-md-6">
      <label for='' class="col-form-label">Add Bulk DIDs (max 1000, emailed CSV report)</label>
      <%= f.number_field :bulk_dids, class: 'form-control', value: '0', min: 0, max: 1000 %>
      
      
        <div id="accordion" role="tablist" aria-multiselectable="true">
          <div class="card card-accordion">
            <div class="card-header" role="tab" id="heading1">
              <h6 class="mb-0">
                <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" class="collapsed" aria-expanded="false" aria-controls="collapse1">
                  Add Bulk DIDs Advanced Options
                </a>
              </h6>
            </div>
            <div id="collapse1" class="collapse" role="tabpanel" aria-labelledby="heading1">
              <div class="card-block" style="border-width: 0px;">
                <%= f.check_box :toll_free, class: 'checkbox-custom form-check-input' %>
                <label for='' class="checkbox-custom-label form-check-label">Toll Free DIDs</label>
              </div>
              <label for='' class="col-form-label">Select States (Local DIDs Only)</label>
              <div class="card-block" style="border-width: 0px;">
                <%= f.collection_check_boxes :selected_states, states, :first, :first do |b| %>
                  <div class="form-group col-md-3 float-left">
                    <%= b.check_box class: 'checkbox-custom form-check-input' %>
                    <%= b.label class: 'checkbox-custom-label form-check-label' %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    
    <div class="from-group col-md-12">
      <p></p>
    </div>
    <div class="from-group">
      <div class="col-md-6 offset-md-1">
        <%= f.submit 'Update', class: 'btn btn-primary btn-default card-btn' %>
      </div>
    </div>
  </div>
<% end %>

app/views/funnels/_index.html.erb
<div id='flash_messages'>
</div>
<h3><%= link_to 'Dashboard', dashboard_path, remote: true, style: 'color:#1da3ed;' %> / <%= link_to 'Funnels', funnels_path, remote: true, style: 'color:#1da3ed;' %> / 
  <% if current_user.campaigns.blank? %>
    <span style='text-decoration: line-through;'>Add New <i class='fa fa-plus-circle'></i></span> (No Destinations)</h3>
  <% else %>
    <%= link_to "Add New <i class='fa fa-plus-circle'></i>".html_safe, new_funnel_path, remote: true, style: 'color:#1da3ed;' %></h3>
  <% end %>
<p> </p>
<div class="orderBox">
  <h4>Funnels</h4>
  <div class="table-responsive">
    <table class="table" id="funnels_table">
      <tbody>
        <% if current_user.funnels.blank? %>
          <thead>
            <tr>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% if current_user.campaigns.blank? %>
            <tr>
              <td style="color:black;">Please create a destination before you create a funnel.</td>
              <td><span style='text-decoration: line-through;'>Add New <i class='fa fa-plus-circle'></i></span></td>
            </tr>
          <% else %>
            <tr>
              <td style="color:black;">Please create your first funnel at your convenience.</td>
              <td><%= link_to "Add New <i class='fa fa-plus-circle'></i>".html_safe, new_funnel_path, remote: true, style: 'color:#1da3ed;' %></td>
            </tr>
          <% end %>
        <% else %>
          <thead>
            <tr>
              <th>Name</th>
              <th>Forwarding Number</th>
              <th>DID</th>
              <th>Vertical</th>
              <th>Type</th>
              <th>Mask Number</th>
              <th></th>
            </tr>
          </thead>
          <% current_user.funnels.each do |funnel| %>
            <tr id='<%= funnel.name %>'>
              <td><%= funnel.name %></td>
              <td><%= funnel.forwarding_number %></td>
              <td>
                <% funnel.dids.each do |did| %>
                  <%= number_to_phone(did.number, area_code: true) %><br />
                <% end %>
              </td>
              <td><%= funnel.vertical.name unless funnel.vertical.blank? %></td>
              <td><%= funnel.routing_type.humanize %></td>
              <td><%= funnel.mask_number %></td>
              <td><%= link_to 'Edit', edit_funnel_path(id: funnel.id), remote: true, style: 'color:black;' %> / <%= link_to 'Delete', funnel_path(id: funnel.id), method: :delete, remote: true, style: 'color:black;', data: { confirm: 'Are you sure? This cannot be undone.' } %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/funnels/_new.html.erb
<div id="campaigns_table" class="display-single_element">
  <%= form_for @funnel, url: funnels_path(@funnel), method: :post, remote: true do |f| %>
    <div class="row" id="funnels_table">    
      <div class="form-group col-md-6">
        <label for='' class="col-form-label">Name</label>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group col-md-6"> 
        <label for='' class="col-form-label">Forwarding Number (Optional)</label>
        <%= f.telephone_field :forwarding_number, class: 'form-control' %>
      </div>
      <div class="from-group col-md-6">
        <div class="selectOptions">
          <label for='' class="col-form-label">Vertical</label>
          <%= f.select :vertical_id, current_user.verticals.collect { |v| [ v.name, v.id ] }, { prompt: 'Select Vertical' }, class: 'form-control select-drop' %>
        </div>
      </div>         
      <div class="from-group col-md-6">
        <div class="selectOptions">
          <label for='' class="col-form-label">Routing Type</label>
          <%= f.select :routing_type, Funnel.routing_types.keys.map { |f| [ f.humanize.titleize, f ] }, { prompt: 'Select Routing Type' }, class: 'form-control select-drop' %>
        </div>
      </div>
      <div class="from-group col-md-6">
        <% if current_user.campaigns.blank? %>
          <p></p>
        <% else %>
          <div class='display-single_element'>
            <p style='color:black;font-size:15px;margin-top:30px;'>Destinations</p>
            <div class='row'>
              <%= f.collection_check_boxes :campaign_ids, current_user.campaigns, :id, :name do |b| %>
                <div class="form-group col-md-6">
                  <%= b.check_box class: 'checkbox-custom form-check-input' %>
                  <%= b.label class: 'checkbox-custom-label form-check-label' %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="from-group col-md-6">
        <div class='display-single_element'>
          <p style='color:black;font-size:15px;margin-top:30px;'>Options</p>
          <div class='row'>
            <div class="from-group col-md-6">
              <%= f.check_box :mask_number, class: 'checkbox-custom form-check-input' %>
              <label for='' class="checkbox-custom-label form-check-label">Mask Number</label>
            </div>
          </div>
        </div>
      </div> 
      <div class="from-group col-md-6">
        <div class="selectOptions">
          <label for='' class="col-form-label">Select/Buy Single Inbound DID</label>
            <%= f.select :did_ids, Did.where(funnel_id: nil).order(Arel.sql('RAND()')).limit(6).collect { |d| [ number_to_phone(d.number, area_code: true), d.id ] }, { prompt: 'Pick An Available DID' }, class: 'form-control select-drop' %>
        </div>
      </div>
      <div class="from-group col-md-6">
        <label for='' class="col-form-label">Buy Bulk DIDs (max 1000, emailed CSV report)</label>
        <%= f.number_field :bulk_dids, class: 'form-control', value: '0', min: 0, max: 1000 %>
        
        
          <div id="accordion" role="tablist" aria-multiselectable="true">
            <div class="card card-accordion">
              <div class="card-header" role="tab" id="heading1">
                <h6 class="mb-0">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" class="collapsed" aria-expanded="false" aria-controls="collapse1">
                    Buy Bulk DIDs Advanced Options
                  </a>
                </h6>
              </div>
              <div id="collapse1" class="collapse" role="tabpanel" aria-labelledby="heading1">
                <div class="card-block" style="border-width: 0px;">
                  <%= f.check_box :toll_free, class: 'checkbox-custom form-check-input' %>
                  <label for='' class="checkbox-custom-label form-check-label">Toll Free DIDs</label>
                </div>
                <label for='' class="col-form-label">Select States (Local DIDs Only)</label>
                <div class="card-block" style="border-width: 0px;">
                  <%= f.collection_check_boxes :selected_states, states, :first, :first do |b| %>
                    <div class="form-group col-md-3 float-left">
                      <%= b.check_box class: 'checkbox-custom form-check-input' %>
                      <%= b.label class: 'checkbox-custom-label form-check-label' %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        
      </div>
      <div class="from-group col-md-12">
        <p></p>
      </div>
      <div class="from-group">
        <div class="col-md-6 offset-md-1">
          <%= f.submit 'Create', class: 'btn btn-primary btn-default card-btn' %>
        </div>
      </div>    
    </div>
  <% end %>
</div>

app/views/funnels/buy_dids.js.erb
$('#bulk_buy_flash_messages').replaceWith("<div id='bulk_buy_flash_messages'> <%= j render partial: 'flash_messages' %> </div>");

app/views/funnels/create.js.erb
<% if @error %>
  <% if @funnel %>
<% messages = @funnel.errors.map { |key, message| content_tag(:li, message) }.join.html_safe %>
    <% flash[:error] = messages %>
    $("#flash_messages").replaceWith("<div id='flash_messages'> <%= j render partial: 'flash_messages' %> </div>");
    <% @funnel.errors.details.each do |key, message| %>
      $("#funnel_<%= key %>").addClass('is-invalid');
    <% end %>
  <% else %>
    $("#flash_messages").replaceWith("<div id='flash_messages'> <%= j render partial: 'flash_messages' %> </div>");
  <% end %>
<% else %>
  $("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");
<% end %>

app/views/funnels/destroy.js.erb
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");

app/views/funnels/edit.js.erb
$("#funnels_table").replaceWith("<%= j render partial: 'edit' %>");
$('.select-drop').selectbox();

app/views/funnels/index.js.erb
$("#dashboard_menu").replaceWith("<div id='dashboard_menu'> <%= j render partial: '/dashboards/menu' %> </div>");
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");

app/views/funnels/new.js.erb
$("#funnels_table").replaceWith("<%= j render partial: 'new' %>");
$('.select-drop').selectbox();

app/views/funnels/update.js.erb
$("#dashboard_workspace").replaceWith("<div id='dashboard_workspace'> <%= j render partial: 'index' %> </div>");