config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#redirect_to_welcome' 
  get '/welcome' => 'pages#index'
  
  # These routes are for showing users a login form, logging them in, and logging them out:
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  # These routes will be for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user:
  resources :users
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  # This route is for showing users their dashboard:
  get '/dashboard' => 'dashboards#show'
  post '/dashboard' => 'dashboards#show'
  post 'filter_dids', to: 'dashboards#filter_dids', as: :filter_dids
  post 'reassign_dids', to: 'dashboards#reassign_dids', as: :reassign_dids
  
  # These routes are used for email validation links:
  get '/emailconfirmation' => 'email_confirmations#update'
  get '/sendemailverify' => 'email_confirmations#create'
  
  # These routes are used for forgetten password resets:
  get 'password_resets/new'
  get '/passwordreset' => 'password_resets#edit'
  post '/passwordreset' => 'password_resets#update'
  get '/requestreset' => 'password_resets#new'
  post '/requestreset' => 'password_resets#create'
  
  resources :verticals
  
  resources :sources
  
  resources :funnels
  put 'funnel_buy_dids', to: 'funnels#buy_dids', as: :funnel_buy_dids
  
  resources :campaigns do
		member do
			get :contact_history
		end
	end
  
  get '/contacts' => 'contacts#index'
  put '/contacts' => 'contacts#update'
  
  get '/backoffice' => 'backoffice#index'
  
  resources :globals, controller: 'backoffice'
	
	patch '/backoffice' => 'backoffice#update'
	
	resources :backoffice
  
  resources :charges
	
	resources :ivrs
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  #before_action :disable_navbar, only: [:show]
  before_action :authorize, only: [:show]
  
  def show
    user = current_user
    if user.buyer?
      @active = 'buyers'
      @campaign = Campaign.find_by(id: current_user.buyer_campaign_id)
    else
      @active = params[:button]
      @active = 'destinations' if @active.blank?
			
			# Redirect to payment screen if zero balance
			if user.balance < 0.to_d
				@active = 'charges'
				flash[:error] = 'Please fund your account.'
			end
    end
  end
  
  def filter_dids
    funnel = Funnel.find_by_id(params[:did_filter][:funnel_id])
    vertical = Vertical.find_by_id(params[:did_filter][:vertical_id])
    campaign = Campaign.find_by_id(params[:did_filter][:campaign_id])
    @dids = ''
    
    if funnel
      @dids = funnel.dids
    elsif vertical
      funnels = current_user.funnels
      vertical_funnels = funnels.where(vertical_id: vertical.id)
      @dids = Did.where(funnel_id: vertical_funnels.ids)
    elsif campaign
      funnels = campaign.funnels
      @dids = Did.where(funnel_id: funnels.ids)
    end
    
    Rails.logger.debug(@dids)
    
    respond_to do |format|
      format.js { @dids }
    end
  end
  
  def reassign_dids
    funnel = Funnel.find_by_id(params[:reassign_dids][:funnel_id])
    vertical = Vertical.find_by_id(params[:reassign_dids][:vertical_id])
    campaign = Campaign.find_by_id(params[:reassign_dids][:campaign_id])
    dids = Did.where(id: params[:reassign_dids][:dids])
    change_counter = 0
    
    dids.each do |did|
      # Handle funnel mass reassignment
      if did.funnel.id != funnel.id
        unless funnel.blank?
          did.update_attribute(:funnel_id, funnel.id) 
          change_counter += 1
        end
      end
      
      respond_to do |format|
        change_counter = 'No' if change_counter == 0
        format.js { flash[:notice] = "#{change_counter} DIDs edited." }
      end
    end
  end
  
  def campaign_active
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def active(path)
    if current_page?(path)
      return 'btn btn-default active'
    else
      return 'btn btn-default'
    end
  end
  
  def quickview_active(page)
    if @active == page
      return 'btn btn-primary-outlined btn-sm active'
    else
      return 'btn btn-primary-outlined btn-sm'
    end
  end
  
  def fetch_live_calls
    live_calls = Rails.cache.fetch('live_calls', expires_in: 5.seconds) { Vicidial.default_api.all_agents_status }
		#live_calls = Vicidial.default_api.all_agents_status
    campaigns = current_user.campaigns    
    calls_to_display = Array.new
		
    live_calls.each do |live_call|
			live_call.map! { |e| e ? e : '0' }
			
			if Rails.env.development?
				calls_to_display << live_call
			else
				# Check if the live_call agent ID matches the range of possible agent IDs for a given camapign:
      	campaign = campaigns.find_all { |c| live_call[0].to_i.between?( c.vicidial_agent_user.to_i, (c.vicidial_agent_user.to_i + c.concurrent_call_limit.to_i - 1) ) }.first
			end
      unless campaign.blank?
        live_call[0] = campaign.client_did
				live_call.push(campaign.name)
        calls_to_display << live_call
      end
    end
		
		calls_to_display.sort_by! { |x| x[3].to_i } unless calls_to_display.blank?
		
		Rails.logger.debug "calls to display: #{calls_to_display}"
		
    calls_to_display
  end
	
	def setup_status
		html = "<p>".html_safe
		if current_user.campaigns.blank?
			link = link_to('new destination', campaigns_path, remote: true, style: 'color:#1da3ed;')
			html.safe_concat("Your first step in setting up your account is to create a #{link}. ")
		end
		if current_user.funnels.blank?
			link = link_to('new funnel', funnels_path, remote: true, style: 'color:#1da3ed;')
			html.safe_concat("You'll need to set up a #{link} for calls to flow through. ")
		end
		html.safe_concat("</p>")
		html
	end
end

app/views/dashboards/_filter_dids.html.erb
<%= form_for :did_filter, url: filter_dids_path, remote: true do |f| %>
  <div id="filter_dids" role="tablist" aria-multiselectable="true">
    <div class="card card-accordion">
      <div class="card-header" role="tab" id="heading1">
        <h6 class="mb-0">
          <a data-toggle="collapse" data-parent="#filter_dids" href="#collapse2" class="collapsed" aria-expanded="false" aria-controls="collapse2">
            Filter DIDs
          </a>
        </h6>
      </div>
      <div id="collapse2" class="collapse" role="tabpanel" aria-labelledby="collapse2">
        <div class="card-block col-md-6" style="border-width: 0px;">
          <div class="selectOptions">
            <label for='' class="col-form-label">Funnel</label>
            <%= f.collection_select :funnel_id, current_user.funnels, :id, :name, { prompt: 'Select Funnel' }, class: 'form-control select-drop' %>
          </div>
          <div class="selectOptions">
            <label for='' class="col-form-label">Vertical</label>
            <%= f.collection_select :vertical_id, current_user.verticals, :id, :name, { prompt: 'Select Vertical' }, class: 'form-control select-drop' %>
          </div>
          <div class="selectOptions">
            <label for='' class="col-form-label">Destinations</label>
            <%= f.collection_select :campaign_id, current_user.campaigns, :id, :name, { prompt: 'Select Destination' }, class: 'form-control select-drop' %>
          </div>
        </div>
        <div class='row'><br /></div>
        <div class="row form-group col-md-3 float-left">
          <div id='filter_dids_flash_messages'></div>
          <%= button_tag 'submit', class: 'btn btn-primary btn-block', name: 'filter_dids_button', data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> Filtering…" } do %>
            <i class="fa fa-circle-o-notch"></i> Filter DIDs
          <% end %>
        </div>
        <div class='row'></div>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboards/_filtered_dids.html.erb
<div id="dashboard_quickview">
  
  <%= render partial: 'funnels/buy_bulk_dids' %>
  
  <%= render partial: 'filter_dids' %>
  
  <%= form_for :reassign_dids, url: reassign_dids_path, remote: true do |rf| %>
      <div class="col-md-12" style="border-width: 0px;">
        <% unless @dids.blank? %>
        <hr />
        <div class="selectOptions">
          <label for='' class="col-form-label">Reassign Funnel</label>
          <%= rf.collection_select :funnel_id, current_user.funnels, :id, :name, { prompt: 'Select Funnel' }, class: 'form-control select-drop' %>
        </div>
        <div class="selectOptions">
          <label for='' class="col-form-label">Reassign Vertical</label>
          <%= rf.collection_select :vertical_id, current_user.verticals, :id, :name, { prompt: 'Select Vertical' }, class: 'form-control select-drop' %>
        </div>
        <div class="selectOptions">
          <label for='' class="col-form-label">Reassign Destinations</label>
          <%= rf.collection_select :campaign_id, current_user.campaigns, :id, :name, { prompt: 'Select Destination' }, class: 'form-control select-drop' %>
        </div>
      </div>
      <div class='row'><br /></div>
      <div class='row'></div>
    <% end %>

    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Select <button type="button" id="check_all" class="btw">All</button></th>
            <th>DID</th>
            <th>Avg Time</th>
            <th>Sold</th>
            <th>B Sold</th>
            <th>V Sold</th>
            <th>Unsold</th>
            <th>Unique</th>
            <th>Funnel</th>
            <th>Vertical / Source</th>
            <th>Export</th>
          </tr>
        </thead>
        <tbody>
          <% if @dids.blank? %>
            <tr>
              <td>No DIDs Found</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          <% else %>
            <% @dids.includes(:funnel).each do |did| %>
              <tr>
                <td><%= rf.check_box(:dids, { multiple: true }, did.id, false) %></td>
                <td><%= number_to_phone(did.number, area_code: true) %></td>
                <td>0</td>
                <td><%= number_with_delimiter(did.sold_count) %></td>
                <td>0</td>
                <td>0</td>
                <td><%= number_with_delimiter(did.calls_count - did.sold_count) %></td>
                <td><%= number_with_delimiter(did.calls_count) %></td>
                <td><%= did.funnel.name %></td>
                <td><%= did.funnel.vertical.name %> / N/A</td>
                <td><i class="fa fa-arrow-circle-o-down"></i></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <div class='row'><br /></div>
    <div class="row form-group col-md-3 float-left">
      <div id='reassign_dids_flash_messages'></div>
      <%= button_tag 'submit', class: 'btn btn-primary btn-block', name: 'reassign_dids_button', data: { disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> Filtering…" } do %>
        <i class="fa fa-circle-o-notch"></i> Reassign DIDs
      <% end %>
    </div>
  <% end %>
  
  <script>
    $('#check_all').on("click", function(){
      var cbxs = $('input[type="checkbox"]');
      cbxs.prop("checked", !cbxs.prop("checked"));
    });
  </script>
  
</div>

app/views/dashboards/_quickview_billing.html.erb
<div id="dashboard_quickview">
  <h4>Billing Transactions (100)</h4>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Amount</th>
          <th>Type</th>
          <th>Destination</th>
          <th>Payment ID</th>
          <th>Customer Phone</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.charges.blank? %>
          <tr>
            <td>No Transactions</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% current_user.charges.recent.each do |charge| %>
            <tr>
              <td><%= charge.updated_at.to_formatted_s(:short) %></td>
              <td><%= number_to_currency(charge.amount, precision: 4) %></td>
              <% if charge.stripe_token.blank? %>
                <td>Debit</td>
                <td><%= charge.contact.campaign.client_did %></td>
                <td>N/A</td>
                <td><%= number_to_phone(charge.contact.phone_number, area_code: true) %></td>
              <% else %>
                <td>Credit</td>
                <td>N/A</td>
                <td><%= charge.stripe_token %></td>
                <td>N/A</td>
              <% end %>
              <td></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/_quickview_charges.html.erb
<div id="dashboard_quickview">
  <div class="row">
    <div class="col-md-8">
      <div class="innerWrapper clearfix stepsPage">
        <div class="row progress-wizard" style="border-bottom:0;">
          
          <div class="col-4 progress-wizard-step active">
            <div class="text-center progress-wizard-stepnum">Payment Amount</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="/dashboard?button=charges" class="progress-wizard-dot"></a>
          </div>
          
          <div class="col-4 progress-wizard-step disabled">
            <div class="text-center progress-wizard-stepnum">Card Info</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="/dashboard?button=charges" class="progress-wizard-dot"></a>
          </div>

          <div class="col-4 progress-wizard-step disabled">
            <div class="text-center progress-wizard-stepnum">Receipt</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="/dashboard?button=charges" class="progress-wizard-dot"></a>
          </div>
        </div>

        <div class="page-header">
          <h4>Fund Your Account</h4>
          <%= form_tag charges_path, remote: true do %>
            <div class="from-group col-md-3">
              <%= number_field_tag 'amount', nil, class: 'form-control', min: 5, placeholder: '$' %>
            </div>
            <div class="from-group">
              <div class="col-md-6 offset-md-1">
                <%= button_tag :submit, class: 'btn btn-primary btn-default card-btn' do %>
                   Continue <i class='fa fa-angle-right'></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_quickview_destinations.html.erb
<div id="dashboard_quickview">
  <h4>Destinations</h4>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Avg Time</th>
          <th>Sold</th>
          <th>Sold %</th>
          <th>Unsold</th>
          <th>Unsold %</th>
          <th>Refnd Total</th>
          <th>Refnd %</th>
          <th>Unique Calls</th>
          <th>Balance</th>
          <th>DL</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.campaigns.blank? %>
          <tr>
            <td>No destinations</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% current_user.campaigns.each do |campaign| %>
            <tr>
              <td><%= link_to campaign.name, edit_campaign_path(campaign.id), remote: true, style: 'color:#1da3ed;' %></td>
              <td><%= campaign.talk_average %> secs</td>
              <td><%= campaign.sold_count %></td>
              <td><%= number_to_percentage(campaign.sold_count / (campaign.contacts.size.nonzero? || 1).to_f * 100, precision: 2) %></td>
              <td><%= number_with_delimiter(campaign.contacts.size - campaign.sold_count) %></td>
              <td><%= number_to_percentage((campaign.contacts.size - campaign.sold_count) / (campaign.contacts.size.nonzero? || 1).to_f * 100, precision: 2) %></td>
              <td><%= campaign.refund_count %></td>
              <td><%= number_to_percentage(campaign.refund_count / (campaign.contacts.size.nonzero? || 1).to_f * 100, precision: 2) %></td>
              <td><%= number_with_delimiter(campaign.contacts.size) %></td>
              <td>N/A</td>
              <td><%= link_to "<i class='fa fa-arrow-circle-o-down'></i>".html_safe, contact_history_campaign_path(campaign, format: :csv), style: 'color:black;' %></td>
              <% if campaign.active? %>
                <td><%= link_to "<i class='fa fa-toggle-on' style='color:green;'></i>".html_safe, campaign_path(id: campaign.id, 'campaign[active]' => 'false'), method: :patch %></td>
              <% else %>
                <td><%= link_to "<i class='fa fa-toggle-off' style='color:black;'></i>".html_safe, campaign_path(id: campaign.id, 'campaign[active]' => 'true'), method: :patch %></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/_quickview_dids.html.erb
<div id="dashboard_quickview">
  
  <%= render partial: 'funnels/buy_bulk_dids' %>
  
  <%= render partial: 'filter_dids' %>
  
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>DID</th>
          <th>Avg Time</th>
          <th>Sold</th>
          <th>B Sold</th>
          <th>V Sold</th>
          <th>Unsold</th>
          <th>Unique</th>
          <th>Funnel</th>
          <th>Vertical / Source</th>
          <th>Export</th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.dids.blank? %>
          <tr>
            <td>No DIDs</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% current_user.dids.includes(:funnel).each do |did| %>
            <tr>
              <td><%= number_to_phone(did.number, area_code: true) %></td>
              <td>0</td>
              <td><%= number_with_delimiter(did.sold_count) %></td>
              <td>0</td>
              <td>0</td>
              <td><%= number_with_delimiter(did.calls_count - did.sold_count) %></td>
              <td><%= number_with_delimiter(did.calls_count) %></td>
              <td><%= did.funnel.name %></td>
              <td><%= did.funnel.vertical.name %> / N/A</td>
              <td><i class="fa fa-arrow-circle-o-down"></i></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id='did_flash_messages'>
    <%= render partial: 'flash_messages' %>
  </div>
</div>

app/views/dashboards/_quickview_irvs.html.erb
<div id="dashboard_quickview">
  <h4>DIDs</h4>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Recording</th>
          <th>DIDs Active</th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.dids.blank? %>
          <tr>
            <td>No IVRs</td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% current_user.ivrs.each do |ivr| %>
            <tr>
              <td><%= ivr.name %></td>
              <td><%= ivr.recording %></td>
              <td><%= number_with_delimiter(ivr.did_count) %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/_quickview_menu.html.erb
<%= form_for :dashboard, remote: true do |b| %>
  <div class="btn-group" role="group" aria-label="Quickview Options">
    <%= b.button 'Destinations', value: 'destinations', class: quickview_active('destinations') %>
    <%= b.button 'DIDs', value: 'dids', class: quickview_active('dids'), style: 'margin-left:-4px;' %>
    <%= b.button 'Verticals', value: 'verticals', class: quickview_active('verticals'), style: 'margin-left:-4px;' %>
    <%= b.button 'Sources', value: 'sources', class: quickview_active('sources'), style: 'margin-left:-4px;' %>
    <%= b.button 'Live', value: 'live', class: quickview_active('live'), style: 'margin-left:-4px;' %>
  </div>
<% end %>

app/views/dashboards/_quickview_payment.html.erb
<div id="dashboard_quickview">
  <div class="row">
    <div class="col-md-8">
      <div class="innerWrapper clearfix stepsPage">
        <div class="row progress-wizard" style="border-bottom:0;">
          
          <div class="col-4 progress-wizard-step complete fullBar">
            <div class="text-center progress-wizard-stepnum">Payment Amount</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="/dashboard?button=charges" class="progress-wizard-dot"></a>
          </div>
          
          <div class="col-4 progress-wizard-step complete fullBar">
            <div class="text-center progress-wizard-stepnum">Card Info</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="/dashboard?button=charges" class="progress-wizard-dot"></a>
          </div>

          <div class="col-4 progress-wizard-step active">
            <div class="text-center progress-wizard-stepnum">Receipt</div>
            <div class="progress"><div class="progress-bar"></div></div>
            <a href="/dashboard?button=charges" class="progress-wizard-dot"></a>
          </div>
        </div>

        <div class="page-header">
          <h4>Thank You!</h4>
          <%= number_to_currency(current_user.charges.last.amount) %> has beed added to your account.
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/dashboards/_quickview_sources.html.erb
<div id="dashboard_quickview">
  <h4>Sources</h4>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Avg Time</th>
          <th>Sold</th>
          <th>Unsold</th>
          <th>Unique</th>
          <th>Export</th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.sources.blank? %>
          <tr>
            <td>No sources</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% current_user.sources.each do |source| %>
            <tr>
              <td><%= link_to source.name, edit_source_path(source.id), remote: true, style: 'color:#1da3ed;' %></td>
              <td>0</td>
              <td><%= number_with_delimiter(source.sold_count) %></td>
              <td><%= number_with_delimiter(source.calls_count - source.sold_count) %></td>
              <td><%= number_with_delimiter(source.calls_count) %></td>
              <td><i class="fa fa-arrow-circle-o-down"></i></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/_quickview_verticals.html.erb
<div id="dashboard_quickview">
  <h4>Verticals</h4>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Avg Time</th>
          <th>Sold</th>
          <th>Unsold</th>
          <th>Unique</th>
          <th>Export</th>
        </tr>
      </thead>
      <tbody>
        <% if current_user.verticals.blank? %>
          <tr>
            <td>No verticals</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% else %>
          <% current_user.verticals.each do |vertical| %>
            <tr>
              <td><%= link_to vertical.name, edit_vertical_path(vertical.id), remote: true, style: 'color:#1da3ed;' %></td>
              <td>0</td>
              <td><%= number_with_delimiter(vertical.sold_count) %></td>
              <td><%= number_with_delimiter(vertical.calls_count - vertical.sold_count) %></td>
              <td><%= number_with_delimiter(vertical.calls_count) %></td>
              <td><i class="fa fa-arrow-circle-o-down"></i></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboards/filter_dids.js.erb
$("#dashboard_quickview").replaceWith("<div id='dashboard_quickview'> <%= j render partial: 'filtered_dids' %> </div>");
$('.select-drop').selectbox();

app/views/dashboards/reassign_dids.js.erb
$("#dashboard_quickview").replaceWith("<div id='dashboard_quickview'> <%= j render partial: 'quickview_dids' %> </div>");
$('.select-drop').selectbox();

app/views/dashboards/show.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="page-title">
          <h2>ACCOUNT DASHBOARD</h2>
        </div>
      </div>
      <div class="col-md-6">
        <ol class="breadcrumb float-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active">ACCOUNT DASHBOARD</li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix userProfile">
  <div class="container">
    <div class="row">
      <!-- <%= render partial: '/dashboards/menu' %> -->
    </div>
    <div class="row">
      <!-- <div class="col-xs-12"> -->
        <div class="innerWrapper">
            <%= render partial: 'flash_messages' %>
          <div id='dashboard_workspace'>
            <%= render partial: 'show' %>
          </div>
        </div>
      <!-- </div> -->
    </div>
  </div>
</section>

<%= render partial: 'footer' %>