config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#redirect_to_welcome' 
  get '/welcome' => 'pages#index'
  
  # These routes are for showing users a login form, logging them in, and logging them out:
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  # These routes will be for signup. The first renders a form in the browser, the second will 
  # receive the form and create a user in our database using the data given to us by the user:
  resources :users
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  
  # This route is for showing users their dashboard:
  get '/dashboard' => 'dashboards#show'
  post '/dashboard' => 'dashboards#show'
  post 'filter_dids', to: 'dashboards#filter_dids', as: :filter_dids
  post 'reassign_dids', to: 'dashboards#reassign_dids', as: :reassign_dids
  
  # These routes are used for email validation links:
  get '/emailconfirmation' => 'email_confirmations#update'
  get '/sendemailverify' => 'email_confirmations#create'
  
  # These routes are used for forgetten password resets:
  get 'password_resets/new'
  get '/passwordreset' => 'password_resets#edit'
  post '/passwordreset' => 'password_resets#update'
  get '/requestreset' => 'password_resets#new'
  post '/requestreset' => 'password_resets#create'
  
  resources :verticals
  
  resources :sources
  
  resources :funnels
  put 'funnel_buy_dids', to: 'funnels#buy_dids', as: :funnel_buy_dids
  
  resources :campaigns do
		member do
			get :contact_history
		end
	end
  
  get '/contacts' => 'contacts#index'
  put '/contacts' => 'contacts#update'
  
  get '/backoffice' => 'backoffice#index'
  
  resources :globals, controller: 'backoffice'
	
	patch '/backoffice' => 'backoffice#update'
	
	resources :backoffice
  
  resources :charges
	
	resources :ivrs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  include SessionsHelper

  def authorize
    redirect_to login_url unless helpers.logged_in?
  end
   
  def disable_navbar
    @disable_navbar = true
  end
  
  def redirect_to_welcome
    redirect_to welcome_url
  end
	
	def get_state_area_codes(states)
		area_codes = JSON.parse( File.open(File.join(Rails.root, '/lib', 'us_area_codes.json')).read )
		usa_states = CampaignsController.helpers.states
		full_state_names = Array.new
		usa_states.each { |x| full_state_names.push x.last if states.include?(x.first) }
		matching_acs = Array.new
		area_codes.each { |y| matching_acs.push y.last if full_state_names.include?(y.first) }
		return matching_acs.flatten
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      tag = concat(content_tag(:div, class: 'modal-body') do
				concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissable fade show", role: 'alert') do 
        	concat content_tag(:button, "<span aria-hidden='true'>×</span>".html_safe, type: 'button', 'aria-label' => 'close', class: 'close push-xs-right', data: { dismiss: 'alert' })
        	concat message
	      end)
			end)
    end
    nil
  end
end

app/views/application/_flash_messages.html.erb
<%= flash_messages %>
<% flash.clear %>

app/views/application/_footer.html.erb
  <!-- FOOTER -->
  <div class="footer clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-2 col-xs-12">
        </div>
        <div class="col-sm-2 col-xs-12">
        </div>
        <div class="col-sm-2 col-xs-12">
        </div>
        <div class="col-sm-2 col-xs-12">
          <div class="footerLink">
            <h5>Get in Touch</h5>
            <ul class="list-unstyled">
              <li>Call us at (833) 420-5232</li>
              <li><a href="mailto:info@msmleads.com">info@msmleads.com</a></li>
            </ul>
            <ul class="list-inline">
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-vimeo"></i></a></li>
              <li><a href="#"><i class="fa fa-tumblr"></i></a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-4 col-xs-12">
          <div class="newsletter clearfix">
            <h4>Newsletter</h4>
            <h3>Sign up now</h3>
            <p>Enter your email address and get notified about new updates. We hate spam!</p>
            <div class="input-group">
              <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
              <a href="#" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
            </div>
          </div>  
        </div>
      </div>
    </div>
  </div>
  <!-- COPY RIGHT -->
  <div class="copyRight clearfix">
    <div class="container">
      <div class="row">
        <div class="col-sm-7 col-xs-12">
          <p>&copy; <%= Time.current.year %> <a target="_blank" href="http://msmleads.com/">Veritech, Inc.</a></p>
        </div>
        <div class="col-sm-5 col-xs-12">
          <ul class="list-inline">
            <li><%= image_tag("card1.png") %></li>
            <li><%= image_tag("card2.png") %></li>
            <li><%= image_tag("card3.png") %></li>
            <li><%= image_tag("card4.png") %></li>
          </ul>  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_navbar.html.erb
<a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">dashboard</a>
<ul class="dropdown-menu dropdown-menu-left">
  <li class=""><%= link_to 'Dashboard', dashboard_url, data: { turbolinks: false } %></li>
</ul>
</li>
<% unless current_user.buyer? %>
  <li class="nav-item dropdown megaDropMenu ">
    <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">setup</b></a>
    <ul class="dropdown-menu row">
      <li class="col-md-6 col-12">
        <ul class="list-unstyled">
          <li>Create Settings</li>
          <li class=""><%= link_to '<i class="fa fa-group" aria-hidden="true"></i> New Destination'.html_safe, campaigns_path, remote: true %></li>
          <li class=""><%= link_to '<i class="fa fa-arrows-v" aria-hidden="true"></i> New Vertical'.html_safe, verticals_path, remote: true %></li>
          <li class=""><%= link_to '<i class="fa fa-plus-circle" aria-hidden="true"></i> New Source'.html_safe, sources_path, remote: true %></li>
          <li class=""><%= link_to '<i class="fa fa-filter" aria-hidden="true"></i> New Funnel'.html_safe, funnels_path, remote: true %></li>
        </ul>
      </li>
      <li class="col-md-6 col-12">
        <ul class="list-unstyled">
          <li>Call Distribution</li>
          <li class=""><%= link_to 'IVR', ivrs_path, remote: true %></li>
        </ul>
      </li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">funnels</a>
    <ul class="dropdown-menu dropdown-menu-left">
      <li class=""><%= link_to 'View Funnels', funnels_path, remote: true %></li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">reports</a>
    <ul class="dropdown-menu dropdown-menu-right">
      <li class=""><%= link_to 'Destinations', dashboard_path, remote: true %></li>
      <li class=""><%= link_to 'DIDs', dashboard_path(button: 'dids'), remote: true %></li>
      <li class=""><%= link_to 'Verticals', dashboard_path(button: 'verticals'), remote: true %></li>
  		<li class=""><%= link_to 'Sources', dashboard_path(button: 'sources'), remote: true %></li>
    </ul>
  </li>
<% end %>

app/views/application/_welcome_navbar.html.erb
<a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Why VD CallRouting</a>
<ul class="dropdown-menu dropdown-menu-left">
  <li class=""><%= link_to 'Features', login_url, data: { turbolinks: false } %></li>
  <li><%= link_to 'About', login_url, data: { turbolinks: false } %></li>
  <li><%= link_to 'Contact', login_url, data: { turbolinks: false } %></li>
  <li><%= link_to 'FAQ', login_url, data: { turbolinks: false } %></li>
  <li><%= link_to 'Pricing', login_url, data: { turbolinks: false } %></li>
</ul>